name: weather_icons_flutter
description: Weather icons wrapper
version: 1.0.0
author: Dan Balarin <dan.balarin@gmail.com>
homepage: https://github.com/Kenny11CZ/font_awesome_flutter


dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
  - family: WeatherIcons
    fonts:
      - asset: assets/weathericons-regular.ttf
        weight: 400
