name: weather_icons_flutter
description: Weather icons wrapper
version: 1.0.2
author: Dan Balarin <dan.balarin@gmail.com>
homepage: https://github.com/Kenny11CZ/weather_icons_flutter

environment:
  sdk: '>=1.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
  - family: WeatherIcons
    fonts:
      - asset: assets/weathericons-regular.ttf
        weight: 400
